package gui.windows.login;

import gui.helpers.MessageBox;
import api.Connectionmanager;
import connection.Session;
import java.util.Map;
import thread.AbstractThreadCallbackListener;
import thread.RequestThread;
import util.GUIInterface;
import gui.helpers.ComponentDragMovement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * GUI for logging into Irccloud.
 * @author kulttuuri
 */
public class GUILogin extends javax.swing.JFrame
{
    private int pX = 0;
    private int pY = 0;
    
    public GUILogin()
    {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(getRootPane());
        
        // Titlebar drag handling
        ComponentDragMovement.addDragMovementForComponent(topPanel, this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();
        textfieldUsername = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        passwordfieldPassword = new javax.swing.JPasswordField();
        topPanel = new javax.swing.JPanel();
        buttonCloseApplication = new javax.swing.JButton();
        labelApplicationTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login to Silverline Irccloud desktop client");
        setBackground(new java.awt.Color(20, 61, 94));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(20, 61, 94));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));

        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/user.png"))); // NOI18N
        labelUsername.setText("Username");

        textfieldUsername.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        textfieldUsername.setForeground(new java.awt.Color(34, 34, 34));
        textfieldUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));

        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/key.png"))); // NOI18N
        labelPassword.setText("Password");

        buttonLogin.setBackground(new java.awt.Color(5, 110, 151));
        buttonLogin.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/door_in.png"))); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.setBorderPainted(false);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        passwordfieldPassword.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        passwordfieldPassword.setForeground(new java.awt.Color(34, 34, 34));
        passwordfieldPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));

        topPanel.setBackground(new java.awt.Color(15, 36, 53));

        buttonCloseApplication.setBackground(new java.awt.Color(15, 36, 53));
        buttonCloseApplication.setForeground(new java.awt.Color(168, 69, 66));
        buttonCloseApplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/cross.png"))); // NOI18N
        buttonCloseApplication.setBorderPainted(false);
        buttonCloseApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseApplicationActionPerformed(evt);
            }
        });

        labelApplicationTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelApplicationTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/irccloud_logo.png"))); // NOI18N
        labelApplicationTitle.setText(" Login to Irccloud");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelApplicationTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(buttonCloseApplication)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelApplicationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCloseApplication, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordfieldPassword)
                    .addComponent(textfieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addComponent(labelPassword)
                    .addComponent(labelUsername)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textfieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(labelPassword)
                .addGap(18, 18, 18)
                .addComponent(passwordfieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLogin)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When button login was pressed.
     * @param evt 
     */
    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonLoginActionPerformed
    {//GEN-HEADEREND:event_buttonLoginActionPerformed
        if (textfieldUsername.getText().equals("") || passwordfieldPassword.getText().equals(""))
        {
            MessageBox.notice("Required fields empty", "Username or password cannot be empty.");
        }
        Connectionmanager.getToken();
        Session.setUsername(textfieldUsername.getText());
        Session.setPassword(passwordfieldPassword.getText());
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonCloseApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseApplicationActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonCloseApplicationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUILogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCloseApplication;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel labelApplicationTitle;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordfieldPassword;
    private javax.swing.JTextField textfieldUsername;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    
    /*
    @Override
    public void callbackReceivedFromThread(String type, Object object)
    {
        if (type.equals(RPCSender.RECEIVER_CLASS_TYPE_LOGIN_RESPONSE))
        {
            Map map = (Map)object;
            
            if (map.containsKey("success"))
            {
                boolean success = (Boolean)map.get("success");
                
                if (success == true)
                {
                    //MessageBox.notice("Success", "Login success!");
                    Session.setUsername(textfieldUsername.getText());
                    Session.setSessionID((String)map.get("session"));
                    //Session.setUsername(textfieldUsername.getText());
                    //Session.setSessionID((String)map.get("session"));
                    ircengine.loginSuccesful();
                    this.setVisible(false);
                }
                else
                {
                    MessageBox.notice("Fail", "Login failed. Please check your username and password.");
                }
            }
        }
    }*/
}