package gui.windows.joinNetwork;

import gui.helpers.MessageBox;
import gui.windows.main.GuiMainIrcView;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 * GUI for joining a network.
 * @author Kulttuuri
 */
public class GUIJoinNetwork extends javax.swing.JFrame implements WindowListener {
    private GuiMainIrcView gui;
    
    /**
     * Creates new form GUIJoinNetwork
     */
    private GUIJoinNetwork() {
	initComponents();
    }
    
    public GUIJoinNetwork(GuiMainIrcView gui) {
	this.gui = gui;
	initComponents();
	this.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonJoinNetwork = new javax.swing.JButton();
        textfieldUsername = new javax.swing.JTextField();
        comboboxNetwork = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Join Network");
        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setName("frameJoinNetwork"); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(null);

        buttonJoinNetwork.setText("Join Network");
        buttonJoinNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJoinNetworkActionPerformed(evt);
            }
        });
        getContentPane().add(buttonJoinNetwork);
        buttonJoinNetwork.setBounds(20, 250, 250, 29);
        getContentPane().add(textfieldUsername);
        textfieldUsername.setBounds(20, 130, 250, 28);

        comboboxNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "irc.quakenet.org", "ircnet.org", "testnetwork.com", "irc.irccloud.com" }));
        getContentPane().add(comboboxNetwork);
        comboboxNetwork.setBounds(20, 70, 250, 27);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 120, 16);

        jLabel2.setText("Network");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 210, 16);

        jLabel3.setText("Mitä muuta?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 240, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonJoinNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJoinNetworkActionPerformed
        if (comboboxNetwork.getSelectedItem().equals("")) {
	    MessageBox.notice("Notice", "Please select a network.");
	    return;
	}
        if (textfieldUsername.equals("")) {
	    MessageBox.notice("Notice", "Please choose a nickname.");
	    return;
	
	}
	// TODO: Validate that username is IRC RFC compliant
	
	// TODO: Show loading frame
	
	
	
	this.setVisible(false);
	gui.setVisible(true);
    }//GEN-LAST:event_buttonJoinNetworkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(GUIJoinNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(GUIJoinNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(GUIJoinNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(GUIJoinNetwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
        //</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new GUIJoinNetwork().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonJoinNetwork;
    private javax.swing.JComboBox comboboxNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textfieldUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
	gui.setVisible(true);
	this.setVisible(false);
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
